{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinqsdk\/traceerror\/errordescription-51sd2"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/BlinqSDK\/documentation\/BlinqSDK\/TraceError\/errorDescription-51sd2","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a human-readable description of the error."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"errorDescription","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:8BlinqSDK10TraceErrorO16errorDescriptionSSSgvp","modules":[{"name":"BlinqSDK"}]},"hierarchy":{"paths":[["doc:\/\/BlinqSDK\/documentation\/BlinqSDK","doc:\/\/BlinqSDK\/documentation\/BlinqSDK\/TraceError"]]},"references":{"doc://BlinqSDK/documentation/BlinqSDK":{"role":"collection","title":"BlinqSDK","abstract":[],"identifier":"doc:\/\/BlinqSDK\/documentation\/BlinqSDK","kind":"symbol","type":"topic","url":"\/documentation\/blinqsdk"},"doc://BlinqSDK/documentation/BlinqSDK/TraceError":{"role":"symbol","title":"TraceError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TraceError"}],"abstract":[{"type":"codeVoice","code":"TraceError"},{"type":"text","text":" defines a set of errors that can occur while handling traces."}],"identifier":"doc:\/\/BlinqSDK\/documentation\/BlinqSDK\/TraceError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TraceError"}],"url":"\/documentation\/blinqsdk\/traceerror"},"doc://BlinqSDK/documentation/BlinqSDK/TraceError/errorDescription-51sd2":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns a human-readable description of the error."}],"identifier":"doc:\/\/BlinqSDK\/documentation\/BlinqSDK\/TraceError\/errorDescription-51sd2","kind":"symbol","type":"topic","url":"\/documentation\/blinqsdk\/traceerror\/errordescription-51sd2"}}}